### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER] error 

### ISSUE THREAD

**Issue by brettgus** [ly4k/Certipy#119]
I get a [SSL: WRONG_VERSION_NUMBER] error when trying to connect to the DC.  I double checked it wasn't having a problem with my credentials by providing the wrong credentials, and that gave me a credential error.  I have tried from multiple kali workstations with the same result.

I tried falling back with LDAP and that just times out despite the port being open.

```
proxychains certipy find -vulnerable -u REDACTED@REDACTED -p 'REDACTED' -dc-ip 192.168.REDA.CTED -debug
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
Certipy v4.3.0 - by Oliver Lyak (ly4k)

[+] Authenticating to LDAP server
[proxychains] Strict chain  ...  REDACTED  ...  REDACTED:636  ...  OK
[-] Got error: ('error receiving data: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2548)',)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 89, in receiving
    data = self.connection.socket.recv(self.socket_size)
  File "/usr/lib/python3.10/ssl.py", line 1259, in recv
    return self.read(buflen)
  File "/usr/lib/python3.10/ssl.py", line 1132, in read
    return self._sslobj.read(len)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.10/site-packages/certipy/entry.py", line 60, in main
    actions[options.action](options)
  File "/home/kali/.local/lib/python3.10/site-packages/certipy/commands/parsers/find.py", line 12, in entry
    find.entry(options)
  File "/home/kali/.local/lib/python3.10/site-packages/certipy/commands/find.py", line 1181, in entry
    find.find()
  File "/home/kali/.local/lib/python3.10/site-packages/certipy/commands/find.py", line 165, in find
    connection = self.connection
  File "/home/kali/.local/lib/python3.10/site-packages/certipy/commands/find.py", line 124, in connection
    self._connection.connect()
  File "/home/kali/.local/lib/python3.10/site-packages/certipy/lib/ldap.py", line 77, in connect
    self.connect(version=ssl.PROTOCOL_TLSv1_2)
  File "/home/kali/.local/lib/python3.10/site-packages/certipy/lib/ldap.py", line 128, in connect
    bind_result = ldap_conn.bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 671, in bind
    self.refresh_server_info()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 1427, in refresh_server_info
    self.server.get_info_from_server(self)
  File "/usr/lib/python3/dist-packages/ldap3/core/server.py", line 525, in get_info_from_server
    self._get_schema_info(connection)
  File "/usr/lib/python3/dist-packages/ldap3/core/server.py", line 475, in _get_schema_info
    result = connection.search(schema_entry,
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 853, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 178, in post_send_search
    responses, result = self.get_response(message_id)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 355, in get_response
    responses = self._get_response(message_id, timeout)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 196, in _get_response
    responses = self.receiving()
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 99, in receiving
    raise communication_exception_factory(LDAPSocketReceiveError, type(e)(str(e)))(self.connection.last_error)
ldap3.core.exceptions.LDAPSocketReceiveError: ('error receiving data: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2548)',)
```

**Comment by dashuai785** [comment]
+1

**Comment by brettgus** [comment]
Closing as I no longer have access to the environment
