### ISSUE TITLE
LDAP.py fails with SSL error

### ISSUE THREAD

**Issue by ssabetan** [ly4k/Certipy#15]
With Python 3.7, 3.8 and 3.9, Certipy fails with SSL errors originating from ldap.py.

This seems to be similar to the [this issue ](https://github.com/SecureAuthCorp/impacket/issues/856)with Impacket. Is there a quick fix? 

```
root@workstation:/home/user# certipy domain.org/username@dc.domain.org find
Password:
Traceback (most recent call last):
  File "/usr/local/bin/certipy", line 11, in <module>
    load_entry_point('Certipy==0.2', 'console_scripts', 'certipy')()
  File "/usr/local/lib/python3.9/dist-packages/Certipy-0.2-py3.9.egg/certipy/entry.py", line 170, in main
  File "/usr/local/lib/python3.9/dist-packages/Certipy-0.2-py3.9.egg/certipy/find.py", line 846, in find
  File "/usr/local/lib/python3.9/dist-packages/Certipy-0.2-py3.9.egg/certipy/find.py", line 506, in run
  File "/usr/local/lib/python3.9/dist-packages/Certipy-0.2-py3.9.egg/certipy/find.py", line 495, in connect
  File "/usr/local/lib/python3.9/dist-packages/Certipy-0.2-py3.9.egg/certipy/ldap.py", line 72, in connect
  File "/usr/local/lib/python3.9/dist-packages/impacket/ldap/ldap.py", line 122, in __init__
    self._socket.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'state_machine', 'internal error')]

**Comment by ly4k** [comment]
Hello
If you're having trouble with LDAPS (SSL), you can always fall back to regular LDAP with `-scheme ldap` after the `find` parameter.
