### ISSUE TITLE
find function

### ISSUE THREAD

**Issue by prrsvxt** [ly4k/Certipy#159]
I have an issue when starting certipy find, it looks like this 

AttributeError: module 'enum' has no attribute '_decompose'

**Comment by prrsvxt** [comment]
the full error here: 
[-] Got error: module 'enum' has no attribute '_decompose'
Traceback (most recent call last):
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/commands/find.py", line 782, in security_to_bloodhound_aces
    standard_rights = list(rights["rights"])
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1482, in __iter__
    yield from self._iter_member_(self._value_)
  File "/usr/lib/python3.11/enum.py", line 1369, in _iter_member_by_def_
    yield from sorted(
               ^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1371, in <lambda>
    key=lambda m: m._sort_order_,
                  ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_sort_order_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/entry.py", line 60, in main
    actions[options.action](options)
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/commands/parsers/find.py", line 12, in entry
    find.entry(options)
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/commands/find.py", line 1185, in entry
    find.find()
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/commands/find.py", line 455, in find
    self.output_bloodhound_data(prefix, templates, cas)
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/commands/find.py", line 578, in output_bloodhound_data
    aces = self.security_to_bloodhound_aces(security)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/commands/find.py", line 784, in security_to_bloodhound_aces
    standard_rights = rights["rights"].to_list()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyber-myth/.local/lib/python3.11/site-packages/certipy/lib/constants.py", line 265, in to_list
    members, _ = enum._decompose(cls, self._value_)
                 ^^^^^^^^^^^^^^^
AttributeError: module 'enum' has no attribute '_decompose'

**Comment by Cyb3rC3lt** [comment]
Just to add that it looks like I have that error too. Python 3.11.4 and certipy added via pipx.

**Comment by vaibhav200225** [comment]
Add the below code in /usr/lib/python3.11/enum.py which will solve your problem.

> def _decompose(flag, value):
>     """
>     Extract all members from the value.
>     """
>     # _decompose is only called if the value is not named
>     not_covered = value
>     negative = value < 0
>     members = []
>     for member in flag:
>         member_value = member.value
>         if member_value and member_value & value == member_value:
>             members.append(member)
>             not_covered &= ~member_value
>     if not negative:
>         tmp = not_covered
>         while tmp:
>             flag_value = 2 ** _high_bit(tmp)
>             if flag_value in flag._value2member_map_:
>                 members.append(flag._value2member_map_[flag_value])
>                 not_covered &= ~flag_value
>             tmp &= ~flag_value
>     if not members and value in flag._value2member_map_:
>         members.append(flag._value2member_map_[value])
>     members.sort(key=lambda m: m._value_, reverse=True)
>     if len(members) > 1 and members[0].value == value:
>         # we have the breakdown, don't need the value member itself
>         members.pop(0)
>     return members, not_covered

**Comment by ly4k** [comment]
Fixed in version `4.8.0`
