### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by exploide** [ly4k/Certipy#215]
Certipy does not only depend on `setuptools` during build time, it is also a runtime dependency because in https://github.com/ly4k/Certipy/blob/2780d5361121dd4ec79da3f64cfb1984c4f779c6/certipy/version.py#L1 the `pkg_resources` module is imported, which comes from the `setuptools` package.

If you install Certipy in a fresh environment (e.g. a new virtualenv, or via pipx, at least with Python 3.12) the module is not available and the following error occurs:

```console
$ certipy
Traceback (most recent call last):
  File "/home/user/repos/Certipy/venv/bin/certipy", line 5, in <module>
    from certipy.entry import main
  File "/home/user/repos/Certipy/venv/lib/python3.12/site-packages/certipy/entry.py", line 6, in <module>
    from certipy import version
  File "/home/user/repos/Certipy/venv/lib/python3.12/site-packages/certipy/version.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

As a quick fix, `setuptools` should be added to the `install_requires` section of `setup.py`. However, according to the [setuptools docs](https://setuptools.pypa.io/en/latest/pkg_resources.html) `pkg_resources` is deprecated anyway and should be substituted.

**Comment by AV3T** [comment]
For those that encounter the same issue, I found that injecting setuptools within the certipy-ad pipx environment helps with the error "ModuleNotFoundError: No module named 'pkg_resources":

```bash
pipx inject certipy-ad setuptools
```
