### ISSUE TITLE
Socket ssl wrapping error

### ISSUE THREAD

**Issue by x3by** [ly4k/Certipy#223]
Im trying to find the certs in my lab domain but i get the following issue
```
 $ certipy find -u User1 -p 'Password1!' -target-ip 192.168.1.136 -debug
Certipy v4.8.2 - by Oliver Lyak (ly4k)

[+] Authenticating to LDAP server
[+] Authenticating to LDAP server
[-] Got error: socket ssl wrapping error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/lib/ldap.py", line 77, in connect
    self.connect(version=ssl.PROTOCOL_TLSv1_2)
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/lib/ldap.py", line 136, in connect
    bind_result = ldap_conn.bind()
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ldap3-2.9.1-py3.12.egg/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/usr/lib/python3.12/site-packages/ldap3-2.9.1-py3.12.egg/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3.12/site-packages/ldap3-2.9.1-py3.12.egg/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/entry.py", line 60, in main
    actions[options.action](options)
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/commands/parsers/find.py", line 12, in entry
    find.entry(options)
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/commands/find.py", line 1179, in entry
    find.find()
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/commands/find.py", line 165, in find
    connection = self.connection
                 ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/commands/find.py", line 124, in connection
    self._connection.connect()
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/lib/ldap.py", line 83, in connect
    self.connect(version=ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python3.12/site-packages/certipy_ad-4.8.2-py3.12.egg/certipy/lib/ldap.py", line 136, in connect
    bind_result = ldap_conn.bind()
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ldap3-2.9.1-py3.12.egg/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/usr/lib/python3.12/site-packages/ldap3-2.9.1-py3.12.egg/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3.12/site-packages/ldap3-2.9.1-py3.12.egg/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: [Errno 104] Connection reset by peer
```

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!

Is your LDAPS certificate signed with SHA1 ?

```bash
$ openssl s_client -connect 192.168.1.136:636  2>/dev/null | openssl x509 -noout -text | grep 'Signature Algorithm'
```

:sunflower:

**Comment by x3by** [comment]
sorry i found the problem i forgot to close the issue...thank you

**Comment by x3by** [comment]
with the `-scheme ldap` flag cause in my case i didnt have ldaps
