### ISSUE TITLE
"argument of type 'NoneType' is not iterable" for enabled templates

### ISSUE THREAD

**Issue by frisch-raphael** [ly4k/Certipy#30]
Hi,

First of all, thanks for your awesome tool.
I'm trying to use it but I get the following error. Any idea on what could be going wrong ? 

```
└─# 
Certipy v2.0.5 - by Oliver Lyak (ly4k)

[*] Finding certificate templates
[+] Authenticating to LDAP server
[+] Authenticating to LDAP server
[+] Bound to ldaps://192.168.x.x - ssl
[+] Default path: DC=domain,DC=local
[+] Configuration path: CN=Configuration,DC=domain,DC=local
[*] Found 33 certificate templates
[*] Finding certificate authorities
[*] Found 2 certificate authorities
[-] Got error: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.5-py3.9.egg/certipy/entry.py", line 62, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.5-py3.9.egg/certipy/find.py", line 734, in entry
    find.find()
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.5-py3.9.egg/certipy/find.py", line 145, in find
    if template.get("name") in templates:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by ly4k** [comment]
Thank you for reporting this. Looking into it! :)

**Comment by frisch-raphael** [comment]
Awesome, it works.
Quite impressed by your response time tbh, big kudos to you :-)

**Comment by ly4k** [comment]
Great, and thanks! :)
