### ISSUE TITLE
missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [ly4k/Certipy#31]
Hey,

I'm currently trying to retrieve a certificate from a CA-Server via 'req' command. Got the following error all the time:

```
[-] Got error: generate_private_key() missing 1 required positional argument: 'backend'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.6-py3.9.egg/certipy/entry.py", line 62, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.6-py3.9.egg/certipy/request.py", line 326, in entry
    request.request()
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.6-py3.9.egg/certipy/request.py", line 213, in request
    csr, key = create_csr(username, alt_name=self.alt_name)
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.6-py3.9.egg/certipy/certificate.py", line 119, in create_csr
    key = generate_rsa_key()
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.6-py3.9.egg/certipy/certificate.py", line 112, in generate_rsa_key
    return rsa.generate_private_key(public_exponent=0x10001, key_size=2048)
TypeError: generate_private_key() missing 1 required positional argument: 'backend'

```

Some idea what the cause could be ? CA, Template and or Altname were specified here.

Greetings

**Comment by S3cur3Th1sSh1t** [comment]
That's correct.

```
pip install cryptography==35.0.0
```

Solved it for me, thanks!

**Comment by Banicaliviu** [comment]
Found this and works for me: 
from cryptography.hazmat.backends import default_backend

kdf obj now looks like this 

kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=480000,
        backend=default_backend()
    )
