### ISSUE TITLE
[*] Trying to get TGT... [-] Got error: <Int32 value object, tagSet <TagSet object...

### ISSUE THREAD

**Issue by valerable** [ly4k/Certipy#37]
Hello, I'm currently experiencing an error with authenticating a certificate from ESC1. See the following:

```
└─$ certipy auth -pfx myusercertificate.pfx
Certipy v2.0.9 - by Oliver Lyak (ly4k)

[*] Using principal: myusercertificate@domain.local
[*] Trying to get TGT...
[-] Got error: <Int32 value object, tagSet <TagSet object, tags 0:0:2-128:32:6>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts -2147483648, 2147483647>>, payload [77]>
[-] Use -debug to print a stacktrace 

```

Here is the output when I add the debug flag:

```
└─$ certipy auth -pfx alexap.pfx -debug
Certipy v2.0.9 - by Oliver Lyak (ly4k)

[+] Trying to resolve 'domain.local' at '192.168.21.10'
[*] Using principal: myusercertificate@domain.local
[*] Trying to get TGT...
[+] Trying to connect to KDC at 192.168.221.11
[+] Server time (UTC): 2022-03-08 21:00:08
[-] Got error: <Int32 value object, tagSet <TagSet object, tags 0:0:2-128:32:6>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts -2147483648, 2147483647>>, payload [77]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/auth.py", line 194, in authenticate
    tgt = sendReceive(encoder.encode(as_req), domain, self.target.target_ip)
  File "/usr/lib/python3/dist-packages/impacket/krb5/kerberosv5.py", line 91, in sendReceive
    raise krbError
impacket.krb5.kerberosv5.KerberosError: <unprintable KerberosError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/entry.py", line 83, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/auth.py", line 438, in entry
    authenticate.authenticate()
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/auth.py", line 196, in authenticate
    if "KDC_ERR_CLIENT_NAME_MISMATCH" in str(e) and not is_key_credential:
  File "/usr/lib/python3/dist-packages/impacket/krb5/kerberosv5.py", line 736, in __str__
    retString = 'Kerberos SessionError: %s(%s)' % (constants.ERROR_MESSAGES[self.error])
KeyError: <Int32 value object, tagSet <TagSet object, tags 0:0:2-128:32:6>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts -2147483648, 2147483647>>, payload [77]>

```
Has any experienced this issue or found a workaround with another tool?

**Comment by ly4k** [comment]
Hello

I haven't seen this before. It looks like a bug in Impacket. It reminds me of the Exchange 2022 bug where the date couldn't fit into a signed 32 bit integer. The error indicates that some value was unpacked outside of the signed 32 bit integer range. Strange. Looking into it.

Oliver

**Comment by ly4k** [comment]
Hello again. More debugging showed that this error can be caused by using a certificate that is not suitable for client authentication. Will do some more testing
