### ISSUE TITLE
ESC4 Shadow auto

### ISSUE THREAD

**Issue by JuraGHH** [ly4k/Certipy#40]
Hi,

I run into the below problem when I run the following command:

certipy shadow auto 'xxxxxxxxxx.xxx.xx/xxxxxxxxx:xxxxxxxxxx@xxx.xxx.xxx.xxx' -account 'xxxxxxxxxx' -debug
Certipy v2.0.9 - by Oliver Lyak (ly4k)
[+] Authenticating to LDAP server
[+] Bound to ldaps://xxx.xxx.xxx.xxx:636 - ssl
[+] Default path: DC=xxxxxxxxxx,DC=xxx,DC=xx
[+] Configuration path: CN=Configuration,DC=xxxxxxxxxx,DC=xxx,DC=xx
[*] Targeting user 'xxxxxxxxxx$'
[*] Generating certificate
[-] Got error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/entry.py", line 83, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/shadow.py", line 436, in entry
    actions[options.shadow_action]()
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/shadow.py", line 185, in auto
    result = self.add_new_key_credential(target_dn, user)
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/shadow.py", line 128, in add_new_key_credential
    cert, key_credential, device_id = self.generate_key_credential(
  File "/usr/local/lib/python3.9/dist-packages/Certipy-2.0.9-py3.9.egg/certipy/shadow.py", line 104, in generate_key_credential
    certificate = X509Certificate2(
  File "/usr/local/lib/python3.9/dist-packages/dsinternals-1.2.4-py3.9.egg/dsinternals/common/cryptography/X509Certificate2.py", line 29, in __init__
    self.certificate.get_subject().CN = subject
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 612, in __setattr__
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]

Cheers

**Comment by ly4k** [comment]
Hello

Thanks for reporting this. I'll look into it!

**Comment by AdrianVollmer** [comment]
I have the same issue. The CN is 66 characters long, but the X509 standard sets a maximum of 64 characters for the CN.

**Comment by ly4k** [comment]
Thanks for reporting. The CN doesn't matter as far as I know, so I'll fix it by setting the CN to just be the name of the user.

**Comment by ly4k** [comment]
Fixed in https://github.com/ly4k/Certipy/commit/defd7f458d8287ed4dc72c5d3164e507d2df3bd9
