### ISSUE TITLE
Got error: 'NoneType' object has no attribute 'request'

### ISSUE THREAD

**Issue by forensic65x** [ly4k/Certipy#45]
I am attempting to perform a certificate request using the current version of certipy.

I've ran the setup and did not see any issues/errors.

When attempting the req I am getting a error concerning the request attribute.

Below is the output from the command as well as the output from the command with the suggested -debug option.

============================

user4@kali:/usr/share/Certipy# certipy req 'domain/usertest:redacted@dc3' -ca ca3 -template User
Certipy v3.0.0 - by Oliver Lyak (ly4k)

[*] Requesting certificate
[-] Failed to get dynamic TCP endpoint for CertSvc
[-] Got error: 'NoneType' object has no attribute 'request'
[-] Use -debug to print a stacktrace

===========================

root@kali-tb:/usr/share/Certipy# certipy req 'domain/usertest:redacted@dc3' -ca ca3 -template User -debug
Certipy v3.0.0 - by Oliver Lyak (ly4k)

[+] Trying to resolve 'dc3' at '192.168.202.2'
[+] Generating RSA key
[*] Requesting certificate
[+] Trying to connect to endpoint: ncacn_np:192.168.0.31[\pipe\cert]
[!] Failed to connect to endpoint ncacn_np:192.168.0.31[\pipe\cert]: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)
[+] Trying to resolve dynamic endpoint 'redacted'
[+] Failed to resolve dynamic endpoint 'redacted'
[-] Failed to get dynamic TCP endpoint for CertSvc
[-] Got error: 'NoneType' object has no attribute 'request'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/Certipy-3.0.0-py3.9.egg/certipy/entry.py", line 85, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.9/dist-packages/Certipy-3.0.0-py3.9.egg/certipy/request.py", line 334, in entry
    request.request()
  File "/usr/local/lib/python3.9/dist-packages/Certipy-3.0.0-py3.9.egg/certipy/request.py", line 256, in request
    response = self.dce.request(request)
AttributeError: 'NoneType' object has no attribute 'request'

**Comment by forensic65x** [comment]
Ok - so both the req and -ca arguments should point to the CA?

ex: certipy req 'domain/usertest:redacted@ca3' -ca ca3 -template User -debug

When I try that, I get the following error:

/usr/share/Certipy# certipy req 'domain/usertest:redacted@cs3' -ca cs3 -template User
Certipy v3.0.0 - by Oliver Lyak (ly4k)

[*] Requesting certificate
[-] Got error: RequestSessionError: code: 0x80070057 - E_INVALIDARG - One or more arguments are invalid.
[-] Use -debug to print a stacktrace

**Comment by ly4k** [comment]
Yes, but the -ca argument should contain the name of the CA. If you don't know the name of the CA, you can use the "find" command against the DC server

**Comment by forensic65x** [comment]
I know the name of the CA - its cs3.  

Should the servername after the @ in the req be the CA or a DC?

**Comment by ly4k** [comment]
Great. So everything worked out? :-)
