### ISSUE TITLE
Got error: 'NoneType' object has no attribute 'owner'

### ISSUE THREAD

**Issue by pdcerone** [ly4k/Certipy#70]
I could be stupid however, I'm running certipy 4.0 using sudo and getting this as a Traceback

```
[*] Trying to get CA configuration for 'redacted-NPS-CA' via RRP
[+] Connected to remote registry at 'NPS.redacted.org' (10.x.x.x)
[*] Got CA configuration for 'redacted-NPS-CA'
[+] Resolved 'NPS.redacted.org' from cache: 10.x.x.x
[+] Connecting to 10.x.x.x:80

File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/entry.py", line 60, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/parsers/find.py", line 12, in entry
    find.entry(options)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 1142, in entry
    find.find()
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 435, in find
    self.output_bloodhound_data(prefix, templates, cas)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 586, in output_bloodhound_data
    aces = self.security_to_bloodhound_aces(security)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 739, in security_to_bloodhound_aces
    owner = self.connection.lookup_sid(security.owner)
AttributeError: 'NoneType' object has no attribute 'owner'


```

thanks for the help

**Comment by SV-ZeroOne** [comment]
I'm also getting a similar error with version 4.0. Version 3.0 still seems to work.

`certipy find -u 'someuser' -p 'somepass' -dc-ip 10.0.0.1 -debug
Certipy v4.0.0 - by Oliver Lyak (ly4k)

[+] Authenticating to LDAP server
[+] Bound to ldaps://10.0.0.1:636 - ssl
[+] Default path: DC=exampledom,DC=local
[+] Configuration path: CN=Configuration,DC=exampledom,DC=local
[*] Finding certificate templates
[*] Found 63 certificate templates
[*] Finding certificate authorities
[*] Found 1 certificate authority
[*] Found 34 enabled certificate templates
[+] Trying to resolve 'exampledomh0stnam3.exampledom.local' at '10.0.0.1'
[*] Trying to get CA configuration for 'exampledom-AD' via CSRA
[+] Trying to get DCOM connection for: 10.0.0.2
[!] Got error while trying to get CA configuration for 'exampledom-AD' via CSRA: CASessionError: code: 0x80070005 - E_ACCESSDENIED - General access denied error.
[*] Trying to get CA configuration for 'exampledom-AD' via RRP
[!] Got error while trying to get CA configuration for 'exampledom-AD' via RRP: The NETBIOS connection with the remote host timed out.
[!] Failed to get CA configuration for 'exampledom-AD'
[!] Failed to get CA security and configuration for 'exampledom-AD': unsupported operand type(s) for &: 'NoneType' and 'int'
[+] Resolved 'exampledomh0stnam3.exampledom.local' from cache: 10.0.0.2
[+] Connecting to 10.0.0.2:80
[!] Failed to lookup user with SID 'S-1-5-21-1624210741-1176850496-7473742-6300'
[!] Failed to lookup user with SID 'S-1-5-21-1624210741-1176850496-7473742-10891'
[!] Failed to lookup user with SID 'S-1-5-21-1613290969-4093516934-3820728569-513'
[!] Failed to lookup user with SID 'S-1-5-21-1613290969-4093516934-3820728569-515'
[!] Failed to lookup user with SID 'S-1-5-21-1624210741-1176850496-7473742-8288'
[-] Got error: 'NoneType' object has no attribute 'owner'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/entry.py", line 60, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/parsers/find.py", line 12, in entry
    find.entry(options)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 1142, in entry
    find.find()
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 435, in find
    self.output_bloodhound_data(prefix, templates, cas)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 586, in output_bloodhound_data
    aces = self.security_to_bloodhound_aces(security)
  File "/usr/local/lib/python3.10/dist-packages/Certipy-4.0.0-py3.10.egg/certipy/commands/find.py", line 739, in security_to_bloodhound_aces`

**Comment by l0wc0ster** [comment]
got the same error

**Comment by ly4k** [comment]
Thank you for reporting this. Fixed in https://github.com/ly4k/Certipy/commit/63847f7ed66b8d94718bc84a2a3746171b70a38f
